
#.
#CEC blocks comportements
[kinetics]

	[kinetics.stressValues]

		#.
		#.
		#kinetic stats
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				white_encased_shaft = 0.0
				brown_encased_large_cogwheel = 0.0
				pink_encased_cogwheel = 0.0
				magenta_encased_cogwheel = 0.0
				purple_encased_cogwheel = 0.0
				blue_encased_shaft = 0.0
				gray_encased_large_cogwheel = 0.0
				black_encased_cogwheel = 0.0
				blue_encased_cogwheel = 0.0
				gray_encased_cogwheel = 0.0
				lime_encased_cogwheel = 0.0
				green_encased_cogwheel = 0.0
				light_blue_encased_cogwheel = 0.0
				light_gray_encased_large_cogwheel = 0.0
				cyan_encased_cogwheel = 0.0
				orange_encased_large_cogwheel = 0.0
				pink_encased_large_cogwheel = 0.0
				light_gray_encased_shaft = 0.0
				white_encased_cogwheel = 0.0
				orange_encased_shaft = 0.0
				green_encased_shaft = 0.0
				light_blue_encased_large_cogwheel = 0.0
				cyan_encased_large_cogwheel = 0.0
				magenta_encased_shaft = 0.0
				orange_encased_cogwheel = 0.0
				red_encased_shaft = 0.0
				rgb_encased_shaft = 0.0
				red_encased_large_cogwheel = 0.0
				yellow_encased_large_cogwheel = 0.0
				rgb_encased_large_cogwheel = 0.0
				green_encased_large_cogwheel = 0.0
				white_encased_large_cogwheel = 0.0
				brown_encased_shaft = 0.0
				light_blue_encased_shaft = 0.0
				yellow_encased_cogwheel = 0.0
				brown_encased_cogwheel = 0.0
				black_encased_shaft = 0.0
				blue_encased_large_cogwheel = 0.0
				purple_encased_shaft = 0.0
				black_encased_large_cogwheel = 0.0
				light_gray_encased_cogwheel = 0.0
				red_encased_cogwheel = 0.0
				cyan_encased_shaft = 0.0
				gray_encased_shaft = 0.0
				lime_encased_large_cogwheel = 0.0
				rgb_encased_cogwheel = 0.0
				lime_encased_shaft = 0.0
				magenta_encased_large_cogwheel = 0.0
				pink_encased_shaft = 0.0
				purple_encased_large_cogwheel = 0.0
				yellow_encased_shaft = 0.0

